on: 
  push: 
    branches: [dev] 
    paths: 
    - 'factorial.py' 
    - 'lint.py' 
    - 'requirements.txt'
jobs: 
  build:
    runs-on: ubuntu:22.04
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.8 
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install pylint 
        pip install -r requirements.txt
    - name: Regression test
      run: | 
        python lint.py 
